#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#
nohup java -Dzkmongomaps.mongo.host=${OPENSHIFT_MONGODB_DB_HOST} -Dzkmongomaps.mongo.port=${OPENSHIFT_MONGODB_DB_PORT} -Djetty.host=${OPENSHIFT_INTERNAL_IP} -Djetty.port=${OPENSHIFT_INTERNAL_PORT} -jar ${OPENSHIFT_REPO_DIR}target/dependency/jetty-runner.jar --port ${OPENSHIFT_INTERNAL_PORT} --config ${OPENSHIFT_REPO_DIR}src/etc/jetty.xml ${OPENSHIFT_REPO_DIR}/target/zkmongomaps.war > ${OPENSHIFT_DIY_LOG_DIR}server.log 2>&1 &